export interface Product {
  id: number;
  name: string;
  description: string;
  updated: string;
  intelligence: string;
  speed: string;
  price: number;
  input: string[];
  output: string[];
  license: string;
  productLink?: string;
  suitedTasks?: string;
  visibility?: string;
  languages?: string[];
  scalability?: string;
}

export const defaultProducts: Product[] = [
  {
    id: 1,
    name: 'GPT-4 Turbo',
    description: 'Latest OpenAI model with enhanced reasoning and multimodal capabilities',
    updated: 'Dec 15, 2024',
    intelligence: 'Very High',
    speed: 'Fast',
    price: 450,
    input: ['text', 'image'],
    output: ['text'],
    license: 'Proprietary',
    languages: ['English'],
    scalability: 'High',
  },
  {
    id: 2,
    name: 'Claude 3 Opus',
    description: 'Anthropic\'s most capable model for complex reasoning tasks',
    updated: 'Mar 4, 2024',
    intelligence: 'Very High',
    speed: 'Fast',
    price: 380,
    input: ['text', 'image'],
    output: ['text'],
    license: 'Proprietary',
    languages: ['English'],
    scalability: 'High',
  },
  {
    id: 3,
    name: 'Gemini Ultra',
    description: 'Google\'s most advanced multimodal AI model',
    updated: 'Feb 8, 2024',
    intelligence: 'Very High',
    speed: 'Fast',
    price: 420,
    input: ['text', 'image', 'audio'],
    output: ['text', 'image'],
    license: 'Proprietary',
    languages: ['English', 'Spanish', 'French', 'German'],
    scalability: 'Higher',
  },
  {
    id: 4,
    name: 'Llama 3 70B',
    description: 'Meta\'s largest open-source language model',
    updated: 'Apr 18, 2024',
    intelligence: 'High',
    speed: 'Medium',
    price: 0,
    input: ['text'],
    output: ['text'],
    license: 'MIT',
    languages: ['English'],
    scalability: 'Medium',
  },
  {
    id: 5,
    name: 'Mistral Large',
    description: 'Efficient reasoning and coding model with strong performance',
    updated: 'Feb 26, 2024',
    intelligence: 'High',
    speed: 'Fast',
    price: 280,
    input: ['text'],
    output: ['text'],
    license: 'Proprietary',
    languages: ['English', 'French'],
    scalability: 'High',
  },
  {
    id: 6,
    name: 'CodeLlama 70B',
    description: 'Specialized code generation and understanding model',
    updated: 'Aug 24, 2023',
    intelligence: 'High',
    speed: 'Medium',
    price: 0,
    input: ['text'],
    output: ['text'],
    license: 'MIT',
    languages: ['English'],
    scalability: 'Medium',
  },
  {
    id: 7,
    name: 'PaLM 2',
    description: 'Google\'s advanced language model with multilingual capabilities',
    updated: 'May 10, 2023',
    intelligence: 'High',
    speed: 'Medium',
    price: 350,
    input: ['text'],
    output: ['text'],
    license: 'Proprietary',
    languages: ['English', 'Spanish', 'French', 'German', 'Chinese'],
    scalability: 'High',
  },
  {
    id: 8,
    name: 'Bard Advanced',
    description: 'Google\'s conversational AI with enhanced reasoning',
    updated: 'Jan 15, 2024',
    intelligence: 'High',
    speed: 'Fast',
    price: 200,
    input: ['text', 'image'],
    output: ['text', 'image'],
    license: 'Proprietary',
  },
  {
    id: 9,
    name: 'Cohere Command',
    description: 'Enterprise-focused language model for business applications',
    updated: 'Nov 20, 2023',
    intelligence: 'High',
    speed: 'Fast',
    price: 320,
    input: ['text'],
    output: ['text'],
    license: 'Proprietary',
  },
  {
    id: 10,
    name: 'Anthropic Claude 3 Sonnet',
    description: 'Balanced performance and speed for general applications',
    updated: 'Mar 4, 2024',
    intelligence: 'High',
    speed: 'Fast',
    price: 250,
    input: ['text', 'image'],
    output: ['text'],
    license: 'Proprietary',
  },
  {
    id: 11,
    name: 'Stable Diffusion XL',
    description: 'Advanced image generation model with high quality output',
    updated: 'Jul 26, 2023',
    intelligence: 'Medium',
    speed: 'Medium',
    price: 180,
    input: ['text', 'image'],
    output: ['image'],
    license: 'MIT',
  },
  {
    id: 12,
    name: 'DALL-E 3',
    description: 'OpenAI\'s latest image generation model',
    updated: 'Oct 3, 2023',
    intelligence: 'High',
    speed: 'Medium',
    price: 400,
    input: ['text'],
    output: ['image'],
    license: 'Proprietary',
  },
  {
    id: 13,
    name: 'Midjourney v6',
    description: 'Premium image generation with artistic capabilities',
    updated: 'Dec 21, 2023',
    intelligence: 'High',
    speed: 'Slow',
    price: 300,
    input: ['text'],
    output: ['image'],
    license: 'Proprietary',
  },
  {
    id: 14,
    name: 'Whisper Large',
    description: 'OpenAI\'s speech recognition and transcription model',
    updated: 'Sep 21, 2022',
    intelligence: 'High',
    speed: 'Fast',
    price: 150,
    input: ['audio'],
    output: ['text'],
    license: 'MIT',
  },
  {
    id: 15,
    name: 'TTS-1',
    description: 'OpenAI\'s text-to-speech model with natural voice synthesis',
    updated: 'Nov 6, 2023',
    intelligence: 'Medium',
    speed: 'Fast',
    price: 120,
    input: ['text'],
    output: ['audio'],
    license: 'Proprietary',
  },
  {
    id: 16,
    name: 'ElevenLabs Voice',
    description: 'Advanced voice cloning and text-to-speech technology',
    updated: 'Jan 30, 2024',
    intelligence: 'Medium',
    speed: 'Fast',
    price: 220,
    input: ['text'],
    output: ['audio'],
    license: 'Proprietary',
  },
  {
    id: 17,
    name: 'Llama 3 8B',
    description: 'Efficient open-source model for resource-constrained environments',
    updated: 'Apr 18, 2024',
    intelligence: 'Medium',
    speed: 'Fast',
    price: 0,
    input: ['text'],
    output: ['text'],
    license: 'MIT',
  },
  {
    id: 18,
    name: 'Mistral 7B',
    description: 'Compact and efficient language model for edge deployment',
    updated: 'Sep 27, 2023',
    intelligence: 'Medium',
    speed: 'Fast',
    price: 0,
    input: ['text'],
    output: ['text'],
    license: 'MIT',
  },
  {
    id: 19,
    name: 'Gemini Pro',
    description: 'Google\'s balanced model for general AI tasks',
    updated: 'Dec 6, 2023',
    intelligence: 'High',
    speed: 'Fast',
    price: 280,
    input: ['text', 'image'],
    output: ['text'],
    license: 'Proprietary',
  },
  {
    id: 20,
    name: 'Claude 3 Haiku',
    description: 'Fast and efficient model for real-time applications',
    updated: 'Mar 4, 2024',
    intelligence: 'Medium',
    speed: 'Fast',
    price: 150,
    input: ['text', 'image'],
    output: ['text'],
    license: 'Proprietary',
  },
  {
    id: 21,
    name: 'GPT-3.5 Turbo',
    description: 'Cost-effective language model for general applications',
    updated: 'Nov 6, 2023',
    intelligence: 'Medium',
    speed: 'Fast',
    price: 200,
    input: ['text'],
    output: ['text'],
    license: 'Proprietary',
  },
  {
    id: 22,
    name: 'Anthropic Claude 2.1',
    description: 'Previous generation model with strong reasoning capabilities',
    updated: 'Nov 21, 2023',
    intelligence: 'High',
    speed: 'Medium',
    price: 180,
    input: ['text'],
    output: ['text'],
    license: 'Proprietary',
  },
  {
    id: 23,
    name: 'Stable Code',
    description: 'Code generation model optimized for programming tasks',
    updated: 'Dec 14, 2023',
    intelligence: 'High',
    speed: 'Fast',
    price: 160,
    input: ['text'],
    output: ['text'],
    license: 'MIT',
  },
  {
    id: 24,
    name: 'Replicate Whisper',
    description: 'Open-source speech recognition with high accuracy',
    updated: 'Oct 15, 2023',
    intelligence: 'Medium',
    speed: 'Medium',
    price: 80,
    input: ['audio'],
    output: ['text'],
    license: 'MIT',
  },
  {
    id: 25,
    name: 'Hugging Face BLOOM',
    description: 'Multilingual language model supporting 46 languages',
    updated: 'Jul 6, 2022',
    intelligence: 'Medium',
    speed: 'Medium',
    price: 0,
    input: ['text'],
    output: ['text'],
    license: 'MIT',
  },
  {
    id: 26,
    name: 'Cohere Generate',
    description: 'Text generation model with strong creative writing capabilities',
    updated: 'Sep 12, 2023',
    intelligence: 'Medium',
    speed: 'Fast',
    price: 120,
    input: ['text'],
    output: ['text'],
    license: 'Proprietary',
  },
  {
    id: 27,
    name: 'Stable Video',
    description: 'Text-to-video generation model for dynamic content',
    updated: 'Nov 21, 2023',
    intelligence: 'Medium',
    speed: 'Slow',
    price: 350,
    input: ['text'],
    output: ['video'],
    license: 'MIT',
  },
  {
    id: 28,
    name: 'Runway Gen-3',
    description: 'Advanced video generation with cinematic quality',
    updated: 'Feb 15, 2024',
    intelligence: 'High',
    speed: 'Slow',
    price: 400,
    input: ['text', 'image'],
    output: ['video'],
    license: 'Proprietary',
  },
  {
    id: 29,
    name: 'Pika Labs',
    description: 'AI-powered video creation and editing platform',
    updated: 'Jan 8, 2024',
    intelligence: 'Medium',
    speed: 'Medium',
    price: 280,
    input: ['text', 'image'],
    output: ['video'],
    license: 'MIT',
  },
  {
    id: 30,
    name: 'Synthesia',
    description: 'AI video generation with human-like avatars',
    updated: 'Mar 1, 2024',
    intelligence: 'Medium',
    speed: 'Medium',
    price: 320,
    input: ['text'],
    output: ['video'],
    license: 'Proprietary',
  },
  {
    id: 31,
    name: 'Jasper AI',
    description: 'Content creation AI for marketing and business writing',
    updated: 'Dec 10, 2023',
    intelligence: 'Medium',
    speed: 'Fast',
    price: 240,
    input: ['text'],
    output: ['text'],
    license: 'Proprietary',
  },
  {
    id: 32,
    name: 'Copy.ai',
    description: 'AI copywriting tool for marketing and sales content',
    updated: 'Nov 28, 2023',
    intelligence: 'Medium',
    speed: 'Fast',
    price: 180,
    input: ['text'],
    output: ['text'],
    license: 'Proprietary',
  },
];

export const getProducts = (): Product[] => {
  if (typeof window === 'undefined') return defaultProducts;
  
  const stored = localStorage.getItem('products');
  if (stored) {
    return JSON.parse(stored);
  }
  
  localStorage.setItem('products', JSON.stringify(defaultProducts));
  return defaultProducts;
}; 